config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'

  devise_for :user

  get 'home/index'
  get 'contact/index'
  get 'about/index'

  resources :users do
    resources :accounts
    resources :tours
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :integer          not null, primary key
#  agency_name  :string
#  bank_detail  :string
#  agency_sms   :string
#  whats_app    :string
#  we_chat      :string
#  agency_email :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  documents    :text
#  quotations   :text
#  country      :string
#  city         :string
#

class Account < ApplicationRecord
	belongs_to :user
	has_many :tours
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tour.rb
# == Schema Information
#
# Table name: tours
#
#  id              :integer          not null, primary key
#  name            :string
#  hotel_rating    :integer
#  number_of_days  :integer
#  number_of_night :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  account_id      :integer
#  description     :text
#

class Tour < ApplicationRecord
	belongs_to :account

	def self.by_country(name)
		joins(:account).where("accounts.country ilike ?",  "%%#{name}%%")
	end

	def self.by_city(name)
		joins(:account).where("accounts.city ilike ?",  "%%#{name}%%")
	end

	def self.by_number_of_day(number)
		where(number_of_days: number)
	end

  def self.by_tour_type(tour_type)
    # where(number_of_days: tour_type)
  end

  def self.by_budget(amount)
    # where(number_of_days: tour_type)
  end

	def self.by_number_of_night(number)
		where(number_of_night: number)
	end

	def self.by_hotel_rate(rate)
		where(hotel_rating: rate)
	end

	def between_dates(field, from = nil, to = nil)
    if from.present? && to.present?
      where(field => from..to)
    elsif from.present?
      where("#{field} >= ?", from)
    elsif to.present?
      where("#{field} <= ?", to)
    end
  end

	def self.permitted_paramsname
	[
		:hotel_rating,
		:number_of_days,
		:number_of_night,
		:description,
		:account_id
	]
	end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tours, dependent: :destroy
  has_many :accounts, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/accounts_controller.rb
class AccountsController < SecureController
	def index
		@user = User.find(params[:user_id])
		@account = @user.accounts.first
		@tours = @account.tours
	end

	def new
		@acount = Account.new
	end

	def create
		@account = Account.new(permitted_params)
		if @account.save
			redirect_to home_index_path
		else
			render :new
		end
	end

	def update
		if Account.update(permitted_params)
			redirect_to home_index_path
		else
			render :edit
		end
	end

	def destory

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def resource_model
    controller_name.classify.constantize
  end

  def resource_class
    resource_model.name.downcase.to_sym
  end

  def resource_permitted_params
    resource_model.permitted_params
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(resource)
    home_index_path
  end

  def permitted_params
    params.require(resource_class).permit(resource_permitted_params)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < SecureController
	def index
		@params = params[:tours_grid]
		if @params
			@days = @params[:by_number_of_day]
			@nights = @params[:by_number_of_day]
      @location = @params[:by_country]
			@hotel = @params[:by_hotel_rate]
		end

		@grids = ToursGrid.new(@params) do |scope|
			scope.paginate(:page => params[:page], :per_page => 10)
    end
	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
  before_action :authenticate_user!

end

app/controllers/tours_controller.rb
class ToursController < SecureController

	def index

	end

end

app/controllers/users_controller.rb
class UsersController < SecureController
  def new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, http_method=nil)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      if http_method
        link_to(link_text, link_path, method: http_method)
      else
        link_to(link_text, link_path)
      end
    end
  end

  def css_class_name
    "#{controller.controller_path.split('/')[0].tr('_', '-')}-#{action_name}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/about/index.html.slim
.row
  .col-md-12
    h1 About us
.row
  .col-md-3
    a.thumbnail href="#" mailto="office@manoa.asia"
      img.img-rounded src="https://goo.gl/Jv3jCZ" alt="Manoa"
.row
  .col-md-6
    p 
      | MANOA is a B2B travel platform based in the Kingdom of Cambodia and soon to be registered in Singapore which connects SME travel companies in Southeast Asia. 
      | The company offers the following services: 
    p - Help SME travel agencies connect with each other instantly 
    p - Allow fast, digital and easy B2B business transactions 
    p Utilizing an untapped niche market and our own developed technologies MANOA will enable SMEs in the region competitive in a world wide market.

hr
.row
  .col-md-12
    h5 MANOA was been founded by
.row
  .col-md-6
    p Mr. Rithy RAY, co-founder & CTO, he has 12 years career in Information Technology and Banking known for bridging the broken link between IT Manager, Credit Card Manager with Office of the CEO. 
  .col-md-6
    p Mr. Thomas Wanhoff, co-founder & CEO, he has experience in the SE travel industry, living and working in SE Asia for 10 years, IT project manager for Vina Consulting (Vietnam), Independent Consultant.

app/views/accounts/index.html.slim
.row
  .col-md-12
    h3= @account.agency_name
.row
  .col-md-3
    .thumbnail href="#" mailto="office@manoa.asia"
      = image_tag "logo.jpg", alt: "Manoa", class: 'img-rounded'
.row
  .col-md-6
    p
      ul.dotted-list
        li
          span Email
          span.value= @account.agency_email
        li
          span Bank Detail
          span.value= "3704 0044 0532 0130 00"
          / @account.bank_detail
        li
          span MANOA Messenger
          span.value
            = link_to "#", class: 'messenger-trigger'
              = "#{['5mn', '3mn', '7mn'].sample} ago"
        li
          span MANOA Video Call
          span.value
            = link_to "#", class: 'video-trigger'
              = "#{['5mn', '3mn', '7mn'].sample} ago"

.row
  .col-md-6
    p
      button.btn.btn-info My Documents
      button.btn.btn-info My Quotations


.messenger.md-whiteframe-z2
  .title
    | Messenger
    button#btn-close.btn.btn-mini.btn-link x
  .body
    .wrapper
      .message-a
        | Hi Mr. B!
    .wrapper
      .message-b
       | Hello Mr. A!
    .wrapper
      .message-a
        | So nice to know you, Mr.B!

.video.video-message.md-whiteframe-z2
  .title
    | Video Call
    button#close-video.btn.btn-mini.btn-link x
  .body
    .wrapper
      .message-a
        | Partner 1
    .wrapper
      .message-a
       | Partner 2
    .wrapper
      .message-a
        | Partner 3

app/views/contact/index.html.slim
.row
  .col-md-12
    h1 Get in touch
.row
  .col-xs-6.col-md-3
    a.thumbnail href="#" mailto="office@manoa.asia"
      img src="https://goo.gl/IUxjSd" alt="Manoa" class="img-circle"
    ul.list-group
      li.list-group-item office@manoa.asia

app/views/home/index.html.slim
.row
  .col-md-6
    = simple_form_for @grids, :method => :get, :url => home_index_path do |f|
      .row
        .col-md-6
          .form-group
            = f.input :by_country, collection: [],  label: 'Destination', input_html: { class: 'form-control input-sm' }, prompt: 'Choose a country ...'
        .col-md-6
          .form-group
            = f.input :by_tour_type, collection: [], label: 'Tour Type', input_html: { class: 'form-control input-sm'}, prompt: 'Choose a tour type ...'
      .row
        .col-md-6
          .form-group
            = f.input :by_number_of_day, collection: 1..10, prompt: 'Select number of day',  label: 'How many days', input_html: { class: 'form-control input-sm' }
        .col-md-6
          .form-group
            = f.input :by_budget, collection: 1..10, prompt: 'Select budget', label: 'Budget', input_html: { class: 'form-control input-sm' }
      .row
        .col-md-6
          = f.submit "Search", class: 'btn btn-primary btn-sm'
          = link_to("Reset", home_index_path, class: 'btn btn-default btn-sm')

.row
  - if @params.present?
    h4= pluralize(@grids.assets.size, 'Listing')
    .row-fluid
      #list-items.list-view
        ul.company-list
          .items
            - logos = ['1.jpg', '2.jpg', '3.png', '4.jpg']
            - statuses = ['active', 'inactive']
            - @grids.assets.each do |tour|
              - @account = tour.account
              li.business-listing.clearfix.status-invite.count
                label.item-label.clearfix.valign
                  .col-sm-1.image.ui-shadow.hidden-xs

                    a= image_tag logos.sample, width: '30px'
                  .col-sm-5.col-xs-10.company.valign
                    h4
                      a
                        / = @account.agency_name
                        - tour.hotel_rating.times do
                          = image_tag 'star', size: '14x14'
                        = " #{tour.name}"
                      small.truncate.block
                        = "in #{@account.city}, #{@account.country}"
                      small.mt
                        = @account.agency_email
                  .col-sm-3.info.hidden-xs.valign

                  .col-sm-1.col-xs-2.text-center.action.valign
                    - if statuses.sample == 'active'
                      .online
                    - else
                      = ['5mn', '3mn', '7mn'].sample
                  .col-sm-1.hidden-xs.info.bg-lighter.valign.go-right
                    = image_tag 'messenger.png', size: '40x40', class: 'icon-messenger messenger-trigger'
                  .col-sm-1.hidden-xs.info.bg-lighter.valign
                    = image_tag 'video_call.jpg', size: '40x40', class: 'video-trigger'
.messenger.md-whiteframe-z2
  .title
    | Messenger
    button#btn-close.btn.btn-mini.btn-link x
  .body
    div.wrapper
      .message-a
        | Hi Mr. A!
    div.wrapper
      .message-b
       | Hello Mr. B!

.video
  .title
    | Video Call
    button#close-video.btn.btn-mini.btn-link x
  div
    =image_tag 'a.jpg', class: 'vi-a'
    =image_tag 'b.png', class: 'vi-b'

javascript:
	populateCountries("tours_grid_by_country", "tours_grid_by_city");

app/views/landing/index.html.slim
.jumbotron
  p MANOA means pineapple in Khmer. We have chosen the pineapple because it is a fruit found all over Asia, but it is also a symbol of hospitality.
  p We at MANOA want to connect people in travel businesses in Asia. We are creating a platform to connect travel business across borders. 
  p Travel agents and tour operators will find each other easily and instantly, get connected and can increase business and profits.

  .well.well-ms Interested? Join the journey by subscribing to our mailing list and become member of the early adopter group.

app/views/layouts/_footer.html.slim
footer.footer
  p © 2017 MANOA.

app/views/layouts/_header.html.slim
/ .navbar.navbar-default
.navbar.mano-navbar
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}"
        = image_tag 'full_logo_white.png', alt: 'Manoa', width: '150px', class: 'logo'
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav

        = nav_link('Search', home_index_path)
        - if user_signed_in?
          = nav_link('Account', user_accounts_path(current_user))
        = nav_link('About', about_index_path)
        = nav_link('My Contact', "#")
        = nav_link('My Transaction', "#")
        = nav_link('News', "#")
        / = nav_link('Contact', contact_index_path)
      ul.nav.navbar-nav.navbar-right
        - if !user_signed_in?
          = nav_link('Login', new_user_session_path)
          = nav_link('Sign up', new_user_registration_path)
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
              = current_user.email
              span.caret
            ul.dropdown-menu role="menu"
              = nav_link('Account', user_accounts_path(current_user))
              = nav_link('Edit profile', edit_user_registration_path)
              li.divider
              = nav_link('Sign Out', destroy_user_session_path, :delete)
      / form.navbar-form.navbar-left role="search"
      /   div.form-group
      /     input.form-control type="text" placeholder="Search"
      /   button type="submit" class="btn btn-default" Submit

app/views/layouts/application.html.slim
html
  head
    title Manoa Demo
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body id=css_class_name
  	/ - if notice
  	/ 	p.alert.alert-success
    /     = notice
		/ - if alert
  	/ 	p.alert.alert-danger
    /     = alert
    .container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'

app/views/tours/index.html.erb
<% form_tag user_tours_path, :method => 'get' do %>
<p>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search", :name => nil %>
</p>
<% end %>